{
 "title": "Plex Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_server_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Library Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plex_library_section_size_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Streams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "plex_sessions_active_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_threads{namespace=\"plex\", container=\"plex\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}