{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mikrotik_system_uptime", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mikrotik_system_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mikrotik_interface_tx_error[$__rate_interval])",
     "legendFormat": "{{interface}}"
    },
    {
     "expr": "rate(mikrotik_interface_rx_error[$__rate_interval]) * -1",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "mikrotik_system_free_hdd_space", "legendFormat": "{{name}} free" },
    {
     "expr": "mikrotik_system_total_hdd_space",
     "legendFormat": "{{name}} total"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(mikrotik_interface_tx_byte[$__rate_interval])",
     "legendFormat": "{{interface}}"
    },
    {
     "expr": "rate(mikrotik_interface_rx_byte[$__rate_interval]) * -1",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}