name: Do I Vote Pipeline
on: push
jobs:
  docker:
    runs-on: arc-runner-set
    container:
      image: gcr.io/kaniko-project/executor
    steps:
      - uses: actions/checkout@v4
      - run: /kaniko/executor
